language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database autoDb;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
